name: Update XML File and Generate JSON

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download XML.gz File
        run: |
          curl -L \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" \
            -H "Referer: https://anidb.net" \
            -H "Accept: application/xml" \
            -o anime-titles.xml.gz \
            https://anidb.net/api/anime-titles.xml.gz

      - name: Decompress XML.gz File
        run: |
          if file anime-titles.xml.gz | grep -q 'gzip compressed data'; then
            gunzip -c anime-titles.xml.gz > anime-titles.xml
          else
            echo "The file is not a valid gzip file"
            exit 1
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Convert XML to JSON
        run: uv run convertXmlToJson.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add anime-titles.xml animes-titles.json
          git commit -m 'Daily update of anime-titles.xml and generated anime-titles.json'
          git push
