name: Update XML File

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download XML.gz File
        run: |
          curl -L -o anime-titles.xml.gz http://anidb.net/api/anime-titles.xml.gz
          file anime-titles.xml.gz

      - name: Decompress XML.gz File
        run: |
          if file anime-titles.xml.gz | grep -q 'gzip compressed data'; then
            gunzip -c anime-titles.xml.gz > anime-titles.xml
          else
            echo "The file is not a valid gzip file"
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add anime-titles.xml
          git commit -m 'Daily update of anime-titles.xml'
          git push
